import React from "react";
import Head from "next/head";

function Meta() {
  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <title>BOR-KUR.PL</title>
    </Head>
  );
}

export default Meta;
